spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      #Enviar mensaje como String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
jwt:
  secret: my-secret-key-for-jwt-generation-mitocode-123456789012345
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.access: DEBUG
produce:
  mark-process-error: false