services:
  postgres-auth-v1:
    image: postgres:15
    container_name: postgres-auth-v1
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "51001:5432"
    volumes:
      - api-auth-service-v1-db-data:/var/lib/postgresql/data
    networks:
      - ms-trabajo-final-jpinto

  postgres-accounting-v1:
    image: postgres:15
    container_name: postgres-order-v1
    restart: always
    environment:
      POSTGRES_DB: accountingdb
      POSTGRES_USER: accountinguser
      POSTGRES_PASSWORD: accountingpass
    ports:
      - "51002:5432"
    volumes:
      - api-accounting-service-v1-db-data:/var/lib/postgresql/data
    networks:
      - ms-trabajo-final-jpinto

  postgres-payment-v1:
    image: postgres:15
    container_name: postgres-payment-v1
    restart: always
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: paymentuser
      POSTGRES_PASSWORD: paymentpass
    ports:
      - "51003:5432"
    volumes:
      - api-payment-service-v1-db-data:/var/lib/postgresql/data
    networks:
      - ms-trabajo-final-jpinto

  postgres-refund-v1:
    image: postgres:15
    container_name: postgres-payment-v2
    restart: always
    environment:
      POSTGRES_DB: refunddb
      POSTGRES_USER: refunduser
      POSTGRES_PASSWORD: refundpass
    ports:
      - "51004:5432"
    volumes:
      - api-refund-service-v1-db-data:/var/lib/postgresql/data
    networks:
      - ms-trabajo-final-jpinto

  postgres-talent-human-v1:
    image: postgres:15
    container_name: postgres-talenthuman-v1
    restart: always
    environment:
      POSTGRES_DB: talenthumandb
      POSTGRES_USER: talenthumanuser
      POSTGRES_PASSWORD: talenthumandbpass
    ports:
      - "51005:5432"
    volumes:
      - api-talent-human-service-v1-db-data:/var/lib/postgresql/data
    networks:
      - ms-trabajo-final-jpinto


  api-eureka-server-v1:
    build:
      context: ../api-eureka-server-v1
      dockerfile: Dockerfile
    container_name: api-eureka-server-v1
    ports:
      - "8761:8761"
    networks:
      - ms-trabajo-final-jpinto

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ms-trabajo-final-jpinto

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: CLIENT://localhost:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: CLIENT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - ms-trabajo-final-jpinto

  mongodb_order_read:
    image: mongo:7.0  # puedes usar otra versión si quieres
    container_name: mongodb_order_read
    ports:
      - "51070:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: order_read
    volumes:
      - mongo_order_read_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ms-trabajo-final-jpinto

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - ms-trabajo-final-jpinto


volumes:
  api-auth-service-v1-db-data:
  api-accounting-service-v1-db-data:
  api-payment-service-v1-db-data:
  api-refund-service-v1-db-data:
  api-talent-human-service-v1-db-data:
  mongo_order_read_data:
  kafka-data:
  prometheus_data:
  grafana_data:
  keycloak_data:
  portainer_data:
  redis_data:

#crear el network de forma manual
#docker network create ms-trabajo-final-jpinto
networks:
  ms-trabajo-final-jpinto:
#    external: true