server:
  port: 50005
  servlet:
    context-path: /api-talent-human
spring:
  profiles:
    active: dev
  application:
    name: api-talent-human-v1
  datasource:
    url: jdbc:postgresql://localhost:51005/talenthumandb
    username: talenthumanuser
    password: talenthumandbpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
        #include: "*" # Exponer todos los endpoints (en producción, es mejor limitar esto a solo los necesarios)
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
logging:
  level:
    com.jpinto.refund: DEBUG
    org.springframework.web: INFO
    org.flywaydb: DEBUG